export const skillGroups = [
  {
    id: "ai-genai",
    title: "AI / GenAI",
    items: [
      "Generative AI",
      "RAG",
      "AI Agents",
      "LLM integrations",
      "Embeddings",
      "Sentence Transformers",
      "Hugging Face",
      "QA Models",
      "LoRA / PEFT",
      "Fine-tuning",
      "Vision-language models",
      "LLM reasoning",
    ],
  },
  {
    id: "ml-cv",
    title: "ML / CV",
    items: [
      "Computer Vision",
      "Document AI",
      "OCR",
      "ResNet50",
      "CNNs",
      "Transfer Learning",
      "CLAHE",
      "Grad-CAM",
      "OpenCV",
    ],
  },
  {
    id: "data",
    title: "Data / Databases",
    items: [
      "FAISS",
      "ChromaDB",
      "TF-IDF",
      "Vector search",
      "Embeddings stores",
      "Relational databases",
    ],
  },
  {
    id: "backend",
    title: "Backend / Engineering",
    items: [
      "Python",
      "FastAPI",
      "REST APIs",
      "Playwright",
      "JavaScript",
      "React",
      "Automation",
      "Dashboards",
    ],
  },
] as const;
